### ISSUE TITLE
Generating unique pages to each of the listings according to a template?

### ISSUE THREAD

**Issue by codeconomy** [adriaanvanrossum/saasforcovid.com#4]
Hi again,

Would you have a suggestion on how to generate unique pages to each of the listings (saas products in your case) according to a template? 
(i.e. not linking out to the different SaaS products (in your case), but to unique pages in saasforcovid.com that would offer more details about each saas product.)

**Comment by adriaandotcom** [comment]
That would be great for the website. Not sure how to get all the content right, you have an idea?

**Comment by codeconomy** [comment]
No idea at all right now.
Just really from top of head:
Guess a template and a static site generator would be needed.
i.e. 

- When using static site generators (like Jekyll), there would be layout templates, and styling files and each page then would be coded with markdown.

- Then when Jekyll would do its thing, it would generate the the final html files for each of the "listings" (saas products in the case of saasforcovid).

- The step to write the different markdown files for each of the "listings" should be automated so one does not need to code each page in markdown.

Having said that, there should be a way of doing this more easily without bringing a parsing engine to complicate things further here :)

Should any other idea come to you or you end up adding pages to saasforcovid, do let me know :)
