### ISSUE TITLE
I want to contribute for translation to Spanish

### ISSUE THREAD

**Issue by johnfelipe** [adriaanvanrossum/saasforcovid.com#7]
How can begin?

**Comment by johnfelipe** [comment]
anyone?

**Comment by adriaandotcom** [comment]
Please check the Telegram group: https://t.me/joinchat/AOpS_1GWEumgdvpczbTlIg

You can ask there, but the project is sleepy ;)

**Comment by johnfelipe** [comment]
dear teach me pls how can translate to es, de and fr
